<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OggVorbisSharp" Version="1.0.1" />
	</ItemGroup>
	
	<ItemGroup>
		<ContentWithTargetPath Include="..\BnkExtractorConsole\Libraries\ogg.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>ogg.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\BnkExtractorConsole\Libraries\vorbis.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>vorbis.dll</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>
	
	<ItemGroup>
	  <EmbeddedResource Include="Ww2ogg\Codebooks\packed_codebooks.bin">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Ww2ogg\Codebooks\packed_codebooks_aoTuV_603.bin">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
